[scripts]
gen_data=gen_gmmaq_data.py
verify=verify_gmmaq_result.py

[gen_data]
params=--group-num:groupNum,--m:m,--n:n,--k:k,--dtype:dtype,--group-list:groupList,--output-dir:$INPUT_DIR

[kernel]
params=groupNum,m,n,k,baseM,baseN,baseK,kAL1,kBL1,scaleKAL1,scaleKBL1,dbL0C,l1BufferStage,dtype,scaleAlg,dstTypeMax,$INPUT_DIR,$OUTPUT_DIR/npu_y.bin,$OUTPUT_DIR/npu_y_scale.bin

[verify]
params=$INPUT_DIR/golden_y.bin,$OUTPUT_DIR/npu_y.bin,$INPUT_DIR/golden_y_scale.bin,$OUTPUT_DIR/npu_y_scale.bin
