[scripts]
gen_data=gen_data_kernel_api.py
verify=verify_result_mx.py

[gen_data]
params=--variant:variant,--m:m,--k:k,--n:n,--output-dir:$INPUT_DIR

[kernel]
params=variant,m,k,n

[verify]
params=$INPUT_DIR/golden_c.bin,$OUTPUT_DIR/npu_out.bin,--dtype:output_dtype
