[scripts]
gen_data=gen_data_cubeonly.py
verify=verify_result_cubeonly.py

[gen_data]
params=--group-num:groupNum,--m:m,--n:n,--k:k,--dtype:dtype,--output-dtype:cType,--layout-b:layoutB,--x1-quant-mode:x1QuantMode,--x2-quant-mode:x2QuantMode,--is-bias:isBias,--group-list-type:groupListType,--single-w:singleW,--group-list:groupList,--output-dir:$OUTPUT_DIR

[kernel]
params=groupNum,m,n,k,baseM,baseN,baseK,kAL1,kBL1,x1QuantMode,x2QuantMode,isBias,dbL0C,groupType,groupListType,singleW,aType,bType,cType,biasType,x2ScaleType,layoutA,layoutB,$OUTPUT_DIR,$OUTPUT_DIR/npu_out.bin

[verify]
params=$OUTPUT_DIR/golden_c.bin,$OUTPUT_DIR/npu_out.bin,--groups:groupNum,--m:m,--n:n,--dtype:cType
