[gen_data]
params=--group-num:groupNum,--m:m,--n:n,--k:k,--dtype:dtype,--layout-b:layoutB,--group-list-type:groupListType,--group-type:groupType,--single-w:singleW,--is-bias:isBias,--group-list:groupList,--output-dir:$OUTPUT_DIR

[kernel]
params=groupNum,m,n,k,baseM,baseN,baseK,kAL1,kBL1,scaleKAL1,scaleKBL1,isBias,dbL0C,l1BufferStage,groupType,groupListType,singleW,dtype,layoutA,layoutB,aFullLoad,$OUTPUT_DIR,$OUTPUT_DIR/npu_out.bin

[verify]
params=$OUTPUT_DIR/golden_c.bin,$OUTPUT_DIR/npu_out.bin,--groups:groupNum,--m:m,--n:n
