[scripts]
gen_data=gen_data.py
verify=verify_result.py

[gen_data]
params=--m:m,--k:k,--n:n,--bias:bias,--a-dtype:a_dtype,--b-dtype:b_dtype,--output-dir:$INPUT_DIR
bool_flags=++trans-a:transA,++trans-b:transB

[kernel]
params=m,k,n,bias,a_dtype,b_dtype,transA,transB,base_m,base_n,base_k,tile_k_l1,scale_k_l1,l1_buffers,db_l0c,a_full_load

[verify]
params=$INPUT_DIR/golden_y.bin,$OUTPUT_DIR/npu_y.bin,$INPUT_DIR/golden_y_scale.bin,$OUTPUT_DIR/npu_y_scale.bin,--dtype:a_dtype
