[scripts]
gen_data=gen_gmm_no_quant_data.py
verify=verify_result.py

[gen_data]
params=--group-type:groupType,--group-list-type:groupListType,--single-x:singleX,--single-weight:singleWeight,--single-y:singleY,--weight-format:weightFormat,--dtype:dtype,--group-num:groupNum,--m:m,--n:n,--k:k,--is-bias:isBias,--has-group-list:hasGroupList,--group-list:groupList,--x-ms:xMs,--output-dir:$OUTPUT_DIR

[kernel]
params=groupNum,groupType,groupListType,singleX,singleWeight,singleY,weightFormat,dtype,m,n,k,isBias,hasGroupList,baseM,baseN,baseK,coreNum,$OUTPUT_DIR,$OUTPUT_DIR/npu_out.bin

[verify]
params=$OUTPUT_DIR/golden_c.bin,$OUTPUT_DIR/npu_out.bin,--dtype:dtype
