[scripts]
gen_data=gen_data_cube.py
verify=verify_result_cube.py

[gen_data]
params=--batch:batch,--m:M,--k:K,--n:N,--bias:bias,--a-type:AType,--b-type:BType,--c-type:CType,--bias-type:biasType,--trans-a:transA,--trans-b:transB,--x1-quant-mode:x1quantmode,--x2-quant-mode:x2quantmode,--x2-scale-type:x2ScaleType,--output-dir:$OUTPUT_DIR

[kernel]
params=batch,M,K,N,AType,BType,CType,bias,biasType,transA,transB,x1quantmode,x2quantmode,x2ScaleType,baseM,baseN,baseK,kL1,$OUTPUT_DIR

[verify]
params=$OUTPUT_DIR/golden_c.bin,$OUTPUT_DIR/npu_out.bin,--batch:batch,--m:M,--n:N,--dtype:CType
