[gen_data]
params=m,k,n,batchA,batchB,batch,transA,transB,dtype,bias

[kernel]
params=m,k,n,batch,batchA,batchB,iterBatchL1,iterBatchL0,transA,transB,dtype,hf32,bias

[verify]
params=m,n,batch,dtype
bool_flags=++hf32:hf32
