[scripts]
gen_data=gen_data.py
verify=verify_result.py

[gen_data]
params=m,n,k,batch,--dtype:a_dtype,--output-dir:$INPUT_DIR

[kernel]
params=m,k,n,batch,a_dtype,b_dtype,c_dtype,transA,transB,format,base_m,base_n,base_k,tile_k_l1,scale_k_l1,l1_buffers,db_l0c,a_full_load

[verify]
params=m,n,k,batch,--output:$OUTPUT_DIR/npu_out.bin,--dtype:c_dtype
