[scripts]
gen_data=gen_gmmfr_data.py
verify=verify_gmmfr_result.py

[gen_data]
params=--group-num:groupNum,--total-m:totalM,--batch:batch,--n:n,--k:k,--dtype:dtype,--output-dtype:outputDtype,--logit-dtype:logitDtype,--row-index-dtype:rowIndexDtype,--group-list-type:groupListType,--group-list:groupList,--output-dir:$OUTPUT_DIR

[kernel]
params=groupNum,totalM,batch,n,k,baseM,baseN,baseK,kAL1,kBL1,scaleKAL1,scaleKBL1,dbL0C,groupListType,dtype,outputDtype,logitDtype,rowIndexDtype,$OUTPUT_DIR,$OUTPUT_DIR/npu_out.bin

[verify]
params=$OUTPUT_DIR/golden_y.bin,$OUTPUT_DIR/npu_out.bin,--dtype:outputDtype
