[scripts]
gen_data=gen_data.py
verify=verify_result.py

[gen_data]
params=--valid-blocks:valid_blocks,--output-dir:$INPUT_DIR

[kernel]
params=valid_blocks

[verify]
params=--golden-dir:$INPUT_DIR,--actual-dir:$OUTPUT_DIR
